[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python3.11 -m ensurepip --upgrade",
    "python3.11 -m pip install --upgrade pip setuptools wheel",
    "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
